apiVersion: v1
kind: Secret
metadata:
    name: mcpo-config
stringData:
    config.json: ENC[AES256_GCM,data:wB+6MVQ1ItHpmJReLMOKU3Pq20lxOqT/n4QlT+8ilsrzSyMK7IZZAlboFmLYlhU2iA+MoPElB6G2WNj/G1VjPniEj6XJ7HNRL05QF9KvblOXUUN1m+mESNQEHE8y/rPlfnEqpuPTWieHbD0dLNLbxXBhX6IlQmMHIAK/OZp351J/cOuyYH6pPRTqGq31sxrh/dV9acYqHskZCS3el9aoSs7lDeVo9xkRyeZwcXr060Sv6Jd7HBEUgheSjNvetpg+6FdruAeYAjpMXsGqD6bBcPqODTWYvqW1lXYsQTSBQSUZit+tk8a/DDgSWrqHj4zdfNtt7XFrLJYQ2eujAZDAKOXGxgbZMsik2IAwSFsElEBG1N38jHTv70V17v7GTOSAmtDPU+yCBVb4B30b8w7JGDzCfAN8L+A6MC7EQNuwBXiH1+EEgxUm/6EX8FB+uJQ8kEPx+gpsSe3R2PGa6M3B3fcQvRK2owuXUCsAHS1VLnRjpcApmckso6OiZFcG453Ogb2EqqnS0KuWoOeO8sEnreSyAACu1CTvLj9NSa5mO6dHwqg4GU2GWuIEEy84rMdObv9yosiOBPcA9Tp5BXMqiqvpbdVLszC1HJo4FbWy4n8vuCyPY8RnnPJxdYLtJZLmiHPAVRtqO0h4NTgQ53F0cUGLOpSsh/lldpZPtQ/6E9JmJwtujZQgZPO2HMw0l16vr421RXabvc4kqmC9LTh6xls87oMAjhn/b2Uky270oNB7z0mvvM8LUHMF6IcXZVRgtzwAm4EFqrAyRn4=,iv:P/M0vo16r1lgvMoFFj16MpHvpaGHaWh40rWpRvcjlPo=,tag:tSYn4ywvSSluCJXtDYckDA==,type:str]
sops:
    lastmodified: "2026-01-02T18:46:11Z"
    mac: ENC[AES256_GCM,data:X4VRPsxdUWbANHFMhVKqgiMfGruWnUjfvzoQjCH3Y3iDe70ru6Xkyth6vqNA4J9f2mOQ6aGEt0JLMDlZl51voFD2Ig48fmK8w67USMMCqSytlgKLR1lVlotYYH+joBsYEEicuHDA9gDsSjdk3uNi0SACGG+8o6E5cWQr93ecEx8=,iv:QI5yVPplP2HW120bM9vOvRDUD4UXyYg6OKeTHffCmks=,tag:WCikqVmPe1dYrDaSWrKGew==,type:str]
    pgp:
        - created_at: "2025-12-30T10:43:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA93hhnb3enmpAQ//U4ibK6GRUhVV3ikf9hydoN0xg3AjAXiRaU4ejQMLUxEY
            7MS3sBbRx7BjusPMZt/c9oEndAX+78e7miNM34I7+FBrsCPfrQzmOWG6D0ZfdUI5
            1TFHWLEPYJxSc5POdlUk5PxwKA99FyTrSl/nUTyVMNZTgsiFmOa5Zxxxg5jxD6oG
            Ac4TA1Jh3CWS+CUR9z9iDjyhYSz67DnCWgy10o0y2cCkPqV68w71rijCPSxXgGVz
            /O5yf+MhfhTWjDL94qIRwwPDs6xGHfDpcJ7Xuro0sO3EsBKUYr6f98XTrO9wn2s3
            sgyRj+EbblzhdkxwyDXYZ1pUuAfSeErU6j8hoHnGdVTJa9gRdTQHSZKPQx0vgCwd
            U0s9EGWpMFlHH8spAQ8meif+F3tYQzFV2vKF0F2rgHjp430sIBjSnL5qJUp8FRFn
            YK82/418CBjjmel8hNMwehM4R264b0AO+iY1xUnuhBYjpn37cDrYlVCm9WZY9M5a
            FOtBUK73AptU+6CVioTiFJzc+oc1yjJI4QTFedej4U2NkyKjx5BGhDZq2z4slRqw
            gv9fpWjoahyfYrb7kOYklevfmmAzOhOIz3ToGtN546i+hV02s3XwW4gri/9u3UpB
            X7ojjRRBShsijkERAebQ6IODusGlZoKgomgflc5xlyLNQZfRMgQ5oWA4A+PrHA3S
            XgFAEdgAa3JoHyQwFPN7fRK9+PSa8gCrGB3uQ8kkVbAT1H0GVG/p5marzRHjxif6
            lXVB/+dIm1kEv6DpYbV4ijddGA3wVfuQvonnVzwxefrRQ+IJiKKlCyl/miz88QA=
            =y6xt
            -----END PGP MESSAGE-----
          fp: B0BEDFFF48F4B4FDE37DDDF9F7612B0CD338046E
        - created_at: "2025-12-30T10:43:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0WjP3VGRkQGAQ/+IK6mPvBqK+g4v0T0+TYVh0+wSruudgXHI9XVJuZxb4Q3
            r1XIxytwlax/FfD7xbPG2M6AeOF64pOOjB5F21A2VtjrPx36ry+0CZXZCQAlADB8
            13ykXLd+9gD7aag+AMDALbVgyfOuxwRM7U0/3BWvuH6BYRUhZFBbgg2UwRd4yp5S
            AQuufKGW5y883hCVlgEFCmkI1cMiJd4NAVSgCL2sOf3n/PtLSi0sfQ0jW13H1+Ak
            H2KuWgt37/kWu4na4UDE9eeEdAMuRBwownpqqNN+lsDQzhc89TScx/J76vrYAiw/
            UN6mRNzm9q83vlGxF3a2mf6gF2FtDnDo9YsmXGFoiMBpSyOheNdf91lS5fn3Ohbh
            71YN5t+bp53zF00GoMiBkiEnf4Nu+MF72EPEOQ0RJ/mhkGxd6fW5d6R0EfEcoz+x
            0QNZUsQwc2N1hkazhzUKmnndiTdwE+Vem9RULh1KeMv8U3bRDXaQx0pSwHxQaIA4
            qic55O1wmvK9A6H7OgOaXJl/kUjZPWTwQMu6/SSNihXHsxcjVykgs26xNVB+rwIy
            v20FIjQLTsmGDHWR1CPD8Hp6TJojpRnbZhuL64vzX3LijokSPLsV8WAmoblc5ta+
            pkb6JHCJCNeTQFmUc76RzK/bu+JzLctG2QXueIQVrFW/2ruWHmuKOTuD2uHhTsrS
            XgGjybdK8ishARlveRiABoMuQE9SzfNjeVFDE+V7dEUH6T+froowwsz7Gm4MFc3a
            86v5b62pULSoo9ez9ZhT7etv7PKbE53m6KBIH5Ybr2kHK01IqzYwBJXGZKqwtyE=
            =cfBm
            -----END PGP MESSAGE-----
          fp: A092F959BA0505A15DD0DE90E7B11D65218B8FD2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
