apiVersion: v1
kind: Secret
metadata:
    name: mcpo-config
stringData:
    config.json: ENC[AES256_GCM,data:NJ6XRmzv20uLjrHj7sRJE9kZ9sb/uJ5PD9XRoT3YdsWay+wa/SsqS57BzTUW5/6j1nH7/s5Bpjpjyzo0OnTSkdishdrXClcuCIht1Njr5jq9lQo6O07ucE1zfyySI7dBqD7zl/74E4mcMf4K4o0XvJAJZFbm5xpZu6U87WMGABRBrY/7EGCR1XTyttiLqXlrDx7Tl6QN7MTfzmaaUKaUr2vNLbpwAUj6HBeGc/6SXVkXaFCuWsL8gJDrZ9mN404AaviM9m8kHRv2/uKllbZgHEN0zanm9SsVN0MqTTG8zpP3U5nI0UQ3V38SKSS0TQ7FmB5zxVEsJusgGVJhGIvpLGfTt3+mkDhIQ3ro/QdIIt1V7TNHFfGJdMCVkIGUhSFBVqzZXOD3OfZGtS9pkuR+DWVcB7m2XJ/TXvHmyAlscIIGvS8gKCjEH2k+qVkcB6MIBsuU3Ewwu7Ua21mMDbw7VItnAsvIs9QnifqVnnK09KwMj4DLNyvPy+M/cw==,iv:j4Z34JpCcF4D+eebN1gIjMtBJZJ+PoSLC46Uc3kgYDU=,tag:EjMp13vok0Sn5JsSRHSVuw==,type:str]
sops:
    lastmodified: "2025-12-30T10:43:49Z"
    mac: ENC[AES256_GCM,data:o0gcYT4P6PFVGNakC8uJ+mX9YWLstUFp1I8SUlIRwq/itScS9IfuLdQpvMziMLQLWA2P/aiT12dkYw1JJxfcG8Dlah9UOosuQzc1rNekbNNkgshkVRoVRKc4NcHkXpZOdApLE3OWqQVcHr3trbW65AV7st3UifUPvQI1pLH90VA=,iv:NY5MgaJB3Ei9PdQZ19Ox6noAjhAciO14jFmTfAL0Ql8=,tag:7Q2Blc7wK2pQoOQTJ/ondw==,type:str]
    pgp:
        - created_at: "2025-12-30T10:43:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA93hhnb3enmpAQ//U4ibK6GRUhVV3ikf9hydoN0xg3AjAXiRaU4ejQMLUxEY
            7MS3sBbRx7BjusPMZt/c9oEndAX+78e7miNM34I7+FBrsCPfrQzmOWG6D0ZfdUI5
            1TFHWLEPYJxSc5POdlUk5PxwKA99FyTrSl/nUTyVMNZTgsiFmOa5Zxxxg5jxD6oG
            Ac4TA1Jh3CWS+CUR9z9iDjyhYSz67DnCWgy10o0y2cCkPqV68w71rijCPSxXgGVz
            /O5yf+MhfhTWjDL94qIRwwPDs6xGHfDpcJ7Xuro0sO3EsBKUYr6f98XTrO9wn2s3
            sgyRj+EbblzhdkxwyDXYZ1pUuAfSeErU6j8hoHnGdVTJa9gRdTQHSZKPQx0vgCwd
            U0s9EGWpMFlHH8spAQ8meif+F3tYQzFV2vKF0F2rgHjp430sIBjSnL5qJUp8FRFn
            YK82/418CBjjmel8hNMwehM4R264b0AO+iY1xUnuhBYjpn37cDrYlVCm9WZY9M5a
            FOtBUK73AptU+6CVioTiFJzc+oc1yjJI4QTFedej4U2NkyKjx5BGhDZq2z4slRqw
            gv9fpWjoahyfYrb7kOYklevfmmAzOhOIz3ToGtN546i+hV02s3XwW4gri/9u3UpB
            X7ojjRRBShsijkERAebQ6IODusGlZoKgomgflc5xlyLNQZfRMgQ5oWA4A+PrHA3S
            XgFAEdgAa3JoHyQwFPN7fRK9+PSa8gCrGB3uQ8kkVbAT1H0GVG/p5marzRHjxif6
            lXVB/+dIm1kEv6DpYbV4ijddGA3wVfuQvonnVzwxefrRQ+IJiKKlCyl/miz88QA=
            =y6xt
            -----END PGP MESSAGE-----
          fp: B0BEDFFF48F4B4FDE37DDDF9F7612B0CD338046E
        - created_at: "2025-12-30T10:43:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0WjP3VGRkQGAQ/+IK6mPvBqK+g4v0T0+TYVh0+wSruudgXHI9XVJuZxb4Q3
            r1XIxytwlax/FfD7xbPG2M6AeOF64pOOjB5F21A2VtjrPx36ry+0CZXZCQAlADB8
            13ykXLd+9gD7aag+AMDALbVgyfOuxwRM7U0/3BWvuH6BYRUhZFBbgg2UwRd4yp5S
            AQuufKGW5y883hCVlgEFCmkI1cMiJd4NAVSgCL2sOf3n/PtLSi0sfQ0jW13H1+Ak
            H2KuWgt37/kWu4na4UDE9eeEdAMuRBwownpqqNN+lsDQzhc89TScx/J76vrYAiw/
            UN6mRNzm9q83vlGxF3a2mf6gF2FtDnDo9YsmXGFoiMBpSyOheNdf91lS5fn3Ohbh
            71YN5t+bp53zF00GoMiBkiEnf4Nu+MF72EPEOQ0RJ/mhkGxd6fW5d6R0EfEcoz+x
            0QNZUsQwc2N1hkazhzUKmnndiTdwE+Vem9RULh1KeMv8U3bRDXaQx0pSwHxQaIA4
            qic55O1wmvK9A6H7OgOaXJl/kUjZPWTwQMu6/SSNihXHsxcjVykgs26xNVB+rwIy
            v20FIjQLTsmGDHWR1CPD8Hp6TJojpRnbZhuL64vzX3LijokSPLsV8WAmoblc5ta+
            pkb6JHCJCNeTQFmUc76RzK/bu+JzLctG2QXueIQVrFW/2ruWHmuKOTuD2uHhTsrS
            XgGjybdK8ishARlveRiABoMuQE9SzfNjeVFDE+V7dEUH6T+froowwsz7Gm4MFc3a
            86v5b62pULSoo9ez9ZhT7etv7PKbE53m6KBIH5Ybr2kHK01IqzYwBJXGZKqwtyE=
            =cfBm
            -----END PGP MESSAGE-----
          fp: A092F959BA0505A15DD0DE90E7B11D65218B8FD2
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
