---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami-mongodb.yaml
  - bitnami-postgresql.yaml
  - bitnami-rabbitmq.yaml
  - bitnami-redis.yaml
  - triggerdotdev-trigger.yaml
