---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: pingcap
  namespace: flux-system
spec:
  type: default
  url: https://charts.pingcap.org
  interval: 10m
  timeout: 3m