---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 3d-print-data.yaml
  - dev-share-files.yaml
  - entertainment-media-ec-files.yaml
  - entertainment-media-files.yaml
  - live-record-ec-files.yaml
  - live-record-files.yaml
  - minecraft-data.yaml
  - minecraft-scripts.yaml
  - other-files.yaml
  - palworld-data.yaml
  - personal-files.yaml
  - personal-media-files.yaml
