# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: basic-auth
  namespace: kube-system
stringData:
  users: ENC[AES256_GCM,data:bGLCeaTxz5mpn3r/vkkut+/u9/DpoAERngKEBWtZSb0gOeGYq9nOlJMc,iv:xpFFMXlHlM+y5yiGiqwSFCbhhS0c3YQXEkJ5VaVtEJ4=,tag:10yFBhYRJhVah/jd1ny34Q==,type:str]
sops:
  kms: [ ]
  gcp_kms: [ ]
  azure_kv: [ ]
  hc_vault: [ ]
  age: [ ]
  lastmodified: "2021-11-05T18:38:11Z"
  mac: ENC[AES256_GCM,data:A4l5SHbd+bLK0xqCNvWFX3rMRnOn0MpPCotq8hC2t+tgREQf9hzd0NWcpd+17LzCxFhla6D/4+6NORQgQwsa106R4dT8AaOZAFbl4eF+HGEIWW2EUuswYjnwXfVZb8+rYwjufAS6Dr4XUL0N0zfPnAdDogLptOLCUZ1JKsItLwc=,iv:UK5WFjWbmtjTDMHEsAErIezYheSUnDlio7vFY0zw3fc=,tag:P15s93xp0QF1r6aWvReTig==,type:str]
  pgp:
    - created_at: "2021-11-05T18:37:49Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA93hhnb3enmpARAAwh2cH2sBlJjX8LiAB8KnYY//noJ2w21k5o32jbAei5Pg
        sxM1wBEfhxqx4W5/QY0vHC8fiNLr7gIdk7QVRznkXzeJy6Aye2VuPuTvmCe6p5YU
        m6SFNl2Cp3beOdrKhKpAsP+7dZxO3MgzVbEZPzsliG970rvxR3Va6XKdB9GVEQKs
        IuFNKMfd/aQSschrQ0NUeEe/L+HiJDwpiQFkUOqUY7JibStzy7/MjcD6aSzUuvqh
        GoLY8PVev/OeTtiVGTmZqiolso7De4geDt72X7ScMun6/bAb4siW2y9/Ts/T42ia
        KkJxnH17bhIZd+Bvea3KfJtUM/i8sFzkvaavQtRwBGkqR8ZdZ8O9iR+0cEdENFyn
        diPBB32/9ek43latSoRS91JtGBEa+bDV1w2PcYCjZOWnVihPohEJIuGhqM9uWeAn
        6e22p/uMsiuRor5dZP0WODp5uqMxRZmgEHtvAfZkyKn9EPL2jH7wWdfIbLlE2Vii
        Wqa/U2CaGZ/InMgwUxbDZhkaQS+sSjJiCjebtqK+RLyIg9F/3KkV880PlzBnNeKQ
        jX5I3JT0hdwocdDk5Z5hNnDkpIupf+677CKdJH4LknvpEMRJqPeaJjoxXdLzokJl
        GobMH+/VGjDbxA9UjbfoIesRWndaG6g+jHdZQ9keZWECvGwaGyOyw3bpqvFbWpDS
        XAE7plVxUWHme/s9Y3VIMPkYGS3NrtcosDppkWL8EqqR6ap5yDE6+EFXbKrBbA8k
        UcZXkR0NMKKaqEo/6WsSmkJQz3sSGq1nyj/s/fbLEh7SlIHbWUc8hksjlABC
        =YKIy
        -----END PGP MESSAGE-----
      fp: B0BEDFFF48F4B4FDE37DDDF9F7612B0CD338046E
    - created_at: "2021-11-05T18:37:49Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQIMA0WjP3VGRkQGARAAo678Uj3VSXWyJZAOrAdICXN5Q3z3aTOuHMrPi94N3Gva
        jXi3VJ4ZFzPkYC6kXG/XFjr3V22/fCd1a4BBHBHeRIboPgVKl+bnjpmDlKUQqapy
        dMmDtAA+7NBeioIqtvyrnFGnHZCu1TKK0UVqjmp08PRtYb+hcCP/ka7SwV62Zkwk
        qusLCpvWsIZV4fyX6nRM0nAfblh/nHdsyjvILz7HCzQevyX/0rtwaS/61kJMYRMh
        2E6PN9y//BC7+2gv4742bbfZP6c4dbHMd5Qzk33HGdCLYJuH2yT0eSitKZPhlUrH
        9xNsnCRJ2z5Hx84k+qVN69B3wMd9qqBLIeWpKFxjNGXwUZ3AuCcj8nxlsdCJpgyk
        5ZcELNN3u3PF8kpbaJe/T7fkMdVWMDgFID6259h3tzhz15Xasvtv8O8zgQKPu73j
        2uJmoVSOViYxRFTJX714stLEWMgrxCddRFeMZbkZH9tlrgPJK3i97hTmrUcs8tZB
        Xq/JxEqzTa71vENX/AW8FQiVIRwM0t2R5nX3uVj2FE3Cv0dvEZ06LrG2nvcL1hWP
        98dlDQKi9J2X/yx5GwcJ4GxGMM6tRNZ8/cbWEvvkUz4eCCIfKcw5bzu4wSpbsj4B
        LbAIEP6EzzoihmfQxTpFm76H65Gw/gvIudTqxX3G4PXyFU+M+jH5yJ2kYkvcOKzS
        XAFaj+68EkJhud5uXU5bb65rIJvzdwNybsZezcMsLtcQkuPuw6s1sAy0QflF1Gf7
        9LdhcMhnXllPEXSCmp/bnZ+L1hbN4SiUexp8POV1UW7T6VCiv8bVPI+8tVq6
        =/1oe
        -----END PGP MESSAGE-----
      fp: A092F959BA0505A15DD0DE90E7B11D65218B8FD2
  encrypted_regex: ^(data|stringData)$
  version: 3.7.1
