---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - public

  - ./virtual-machine/ks.yaml

  - ./3d-print/klipper/voron2/ks.yaml
  - ./3d-print/mainsail/ks.yaml
  - ./3d-print/mobileraker-companion/ks.yaml
  - ./3d-print/spoolman/ks.yaml
  - ./3d-print/octoprint/ks.yaml

  - ./bitwarden/ks.yaml
  - ./dell-idrac-fan-controller/ks.yaml
  - ./tyan-pch-thermal-controller/ks.yaml
  - ./librespeed/ks.yaml
  - ./photoprism/ks.yaml
  - ./resilio-sync/ks.yaml
  - ./samba/ks.yaml
  - ./uptime-kuma/ks.yaml
  - ./nextcloud/ks.yaml
  - ./douyin-live-recorder/ks.yaml
  - ./aria2/ks.yaml
  - ./n8n/ks.yaml
  - ./nexus-repository-manager/ks.yaml
  # - ./sentry/ks.yaml
  - ./gitlab/ks.yaml
  - ./happy-coder/ks.yaml
  - ./immich/ks.yaml
  - ./wechat/ks.yaml
  - ./qq/ks.yaml
  - ./funasr/ks.yaml
  - ./funasr-forced-alignment/ks.yaml
  - ./fun-cosyvoice3-0-5b-2512/ks.yaml
  - ./qwen3-tts-base/ks.yaml
  - ./paddleocr-vl/ks.yaml
  - ./funasr-nano-2512/ks.yaml
  - ./transnetv2-shot-detection-service/ks.yaml
  - ./new-api/ks.yaml
  - ./dev-container/ks.yaml

  - ./mongodb/ks.yaml
  - ./rabbitmq/ks.yaml
  - ./prefect/ks.yaml
  - ./dify/ks.yaml

  - ./control-center/ks.yaml

  - ./bazarr/ks.yaml
  - ./chinese-sub-finder/ks.yaml
  - ./emby/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./jackett/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./jproxy/ks.yaml
  - ./cli-proxy-api/ks.yaml
  - ./searxng/ks.yaml
  - ./lidarr/ks.yaml
  - ./mcpo/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-anime/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-anime/ks.yaml

  - ./minecraft/mc-router/ks.yaml
  - ./minecraft/gregtech-new-horizons/ks.yaml
#  - ./minecraft/pseudos-sandbox/ks.yaml
#  - ./minecraft/ftb-ocean-block/ks.yaml
#  - ./minecraft/evolution-of-the-ages-2/ks.yaml
#  - ./minecraft/mine-space/ks.yaml
#  - ./minecraft/unexpected-farm/ks.yaml
#  - ./minecraft/dawn-craft/ks.yaml
#  - ./minecraft/gear-carol/ks.yaml
#  - ./minecraft/prominence-2/ks.yaml
#  - ./minecraft/all-the-mods-8/ks.yaml
#  - ./minecraft/divine-journey/ks.yaml
#  - ./minecraft/end-of-days-traveller/ks.yaml
#  - ./minecraft/tinkers-heartwork-and-deities/ks.yaml
#  - ./minecraft/unity-craft/ks.yaml
#  - ./minecraft/rlcraft/ks.yaml
#  - ./minecraft/mianmian-craft/ks.yaml
#  - ./minecraft/mc-eternal/ks.yaml
#  - ./minecraft/dragon-dventure/ks.yaml
#  - ./minecraft/stellaris-craft/ks.yaml
#  - ./minecraft/rad2/ks.yaml
#  - ./minecraft/infinity/ks.yaml
#  - ./minecraft/the-winter-frontier/ks.yaml
#  - ./minecraft/better-minecraft/ks.yaml
#  - ./minecraft/naturalism/ks.yaml

#  - ./palworld-llm/ks.yaml
#  - ./palworld-sf/ks.yaml
#  - ./palworld-mianmian/ks.yaml
