---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jackett
  - jellyseerr
  - jproxy
  - overseerr
  - lidarr
  - qbittorrent
  - radarr
  - radarr-anime
  - samba
  - sonarr
  - sonarr-anime
  - media-files.yaml
  - download-files.yaml
