---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - juicefs-volume-hook
  - redis
  - media-erasure-coded-postgresql
  - compressed-files-erasure-coded-postgresql
  - ceph-compressed-files-pool.yaml
  - ceph-juicefs-cache-pool.yaml
  - ceph-media-replicated-pool.yaml
  - namespace.yaml
