---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - redis
  - ceph-application-performace-pool.yaml
  - ceph-compressed-files-pool.yaml
  - ceph-media-ec-pool.yaml
  - ceph-media-replicated-pool.yaml
